changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bugfixes
      labels:
        - bugfix
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
  