name: Release
description: Manages version based on GitHub release and validates against it
inputs:
  path:
    description: 'Path to file containing the version'
    default: "VERSION"
  prefix:
    description: 'Prefix for the version'
    default: "v"
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  pre-release:
    description: 'pre release identifier'
  fail:
    description: 'Unused currently ...'
    default: "true"

outputs:
  version:
    description: 'Version of the release'

runs:
  using: 'node20'
  main: "dist/index.js"
