name: CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build, "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
      - name: Manage release
        uses: drctnl/release@master
        with:
          github-token: ${{ github.token }}
