name: CI/CD

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    name: Build, "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name:
        run: npm ci
      - name: Build
        run: npm run build
      - name: Commit and push distribution changes
        run: |
          git config --global user.name "CI/CD"
          git config --global user.email "drctnl@users.noreply.github.com"
          git add dist
          git commit -a -m "Updated distribution of action." && git push || true

      - uses: drctnl/release@master
